### ISSUE TITLE
Creates sub folder for each file in SRC_FOLDER

### ISSUE THREAD

**Issue by djdiskmachine** [birds-inc/m8-sample-organizer#1]
Input:
SRC_FOLDER set to 
samplelib/Drums/Breaks
DEST_FOLDER set to
samplelib/Drums/BreaksConv

Folder samplelib/Drums/Breaks contains multiple samples:
Adrift Break.wav
Apollo.wav
Back Break 2.wav

Expected behavior:
Samples should end up in root of samplelib/Drums/BreaksConv/

Actual behavior:
Samples are organised like
samplelib/Drums/BreaksConv/Adrift Break.wav/Adrift Break.wav
samplelib/Drums/BreaksConv/Apollo.wav/Apollo.wav
samplelib/Drums/BreaksConv/Back Break 2.wav/Back Break 2.wav

**Comment by birds-inc** [comment]
Ah, gotcha.  This tool currently is designed to convert a top-level path like

```
SRC_FOLDER = samplelib
DEST_FOLDER = samplelib-converted
```

If you point it directly at a folder containing files, it'll end up creating folders for you.

This is legit!  I can modify this to detect when it's cutting a single folder over.

**Comment by djdiskmachine** [comment]
Aha didn't realize it was intended to convert a set of subfolders. I wanted to try it out first before running it on all the things 😅
Yeah please add this clause for converting a single folder, I for one would like this as i'll run it on low-powered SBCs mostly :)
