### ISSUE TITLE
Optimizing path length

### ISSUE THREAD

**Issue by acelot** [birds-inc/m8-sample-organizer#2]
Hi, @birds-inc! Thank you for this fantastic tool! This is a truly useful utility for me. Could you please help me how to deal with long paths in my samples collection?

My samples are stored in a very deeply nested folders like this:

<img width="436" alt="image" src="https://github.com/birds-inc/m8-sample-organizer/assets/1065215/dfc9ba50-45a5-460b-8ec4-fe79817677ad">

The main problem is that the files names are contains the vendor name, pack name and the parent folder name. And even after optimization, the paths are too long.

**Is is possible to trim unnecessary words from file names?**

**Comment by birds-inc** [comment]
Sure, define unnecessary

**Comment by acelot** [comment]
Oh, you mean `STRIKE_WORDS`? I'm a fool, I thought these were the some reserved "meta" words )
Thank you!
